version: '3'
services:
    openmage-notification-jekyll-container:
        build:
            context: .
            dockerfile: .docker/jekyll.dockerfile
        ports:
            - "4000:4000"
        volumes:
            - ./:/app
        working_dir: /app
        entrypoint: "bundle exec jekyll serve --host=0.0.0.0 --force_polling"
